### ISSUE TITLE
MetaMod v1290, last CS2 Update, Fake RCON won't work.

### ISSUE THREAD

**Issue by Porcellacion** [Salvatore-Als/cs2-fake-rcon#11]
Although there was recently a 1.2.1b release, this doesn't seem to work for Linux.

MetaMod simply won't load the plugin properly:
```
May  2 12:19:24:  meta list
May  2 12:19:24:  Listing 2 plugins:
May  2 12:19:24:    [01] <ERROR>
```

I'm confident that the plugin is properly installed.

**Comment by mrc4tt** [comment]
@Porcellacion can you post which error it will say?

Try to load it manually with `meta load`, and post which error.

**Comment by Porcellacion** [comment]
Sure, here you go:
```
May  2 12:39:38:  meta load fake_rcon
May  2 12:39:38:  Failed to load plugin addons/fake_rcon/bin/linuxsteamrt64/fake_rcon (/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by /home/dathost/cs2_linux/game/csgo/addons/fake_rcon/bin/linuxsteamrt64/fake_rcon.so)).
```

**Comment by mrc4tt** [comment]
> May  2 12:39:38:  Failed to load plugin addons/fake_rcon/bin/linuxsteamrt64/fake_rcon (/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by /home/dathost/cs2_linux/game/csgo/addons/fake_rcon/bin/linuxsteamrt64/fake_rcon.so)).
> ```

@Porcellacion I will re-compile it. :) I will let you know **ASAP**

**Comment by mrc4tt** [comment]
@Porcellacion .tar.gz has been updated. =)

Check it, and if it works you can close the issue =)

**Comment by Porcellacion** [comment]
Yes, it works! Brilliant. Thank you :)
