### ISSUE TITLE
bug with windows version

### ISSUE THREAD

**Issue by bigoth** [Salvatore-Als/cs2-fake-rcon#12]
hi there a bug with version of windows. i use plugin with ubuntu and no bug but a mate use with windows 10 and the serveur crash when he try to log  "fake_rcon_password password"

**Comment by BnanZ0** [comment]
Same issue
logs before crashing:
Warning:  Can't add nullptr string to table genericprecache
CEngineServer::PrecacheGeneric: '(null)' overflow, too many decals
ResetBreakpadAppId: Universe is 1 (k_EUniversePublic)
ResetBreakpadAppId: Setting dedicated server app id: 2347773

**Comment by vTeee** [comment]
Can you please it for windows version. It’s been 2 weeks since the issue has been reported. Many thanks

**Comment by mrc4tt** [comment]
> Can you please it for windows version. It’s been 2 weeks since the issue has been reported. Many thanks

It's up to @Salvatore-Als to take a look at the Windows version (**As** I understand it, some code needs to be changed before the Windows version will work again)

**It works perfectly fine on Linux**

**Comment by vTeee** [comment]
Looking forward to it

**Comment by Salvatore-Als** [comment]
Ola, I have to fix but I still have a lot of work, I'll try to do that asap :)

**Comment by vTeee** [comment]
Thank you, please fix when you can. Eagerly waiting for an update

**Comment by vTeee** [comment]
Hi @Salvatore-Als  any updates when you’ll be able to fix it?!?

**Comment by vTeee** [comment]
We are still awaiting for this fix.

**Comment by Salvatore-Als** [comment]
Hi, I have fixed my win/lin env.

Making a fix for csay and working for a fix of fake rcon win version.

**Comment by Salvatore-Als** [comment]
Fixed, please refer to **windows.zip** file https://github.com/Salvatore-Als/cs2-fake-rcon/releases/tag/1.2.1b
https://prnt.sc/_4jQ-34a2Y6d

**Comment by vTeee** [comment]
Thank you so much, it’s working now

**Comment by mrc4tt** [comment]
As this is fixed, we will close the issue. :+1:
