### ISSUE TITLE
Doesn't work after Armory update

### ISSUE THREAD

**Issue by vcsoares1** [Salvatore-Als/cs2-fake-rcon#14]
Hello,

Can you fix that? I really appreciate your plugin, but after Armory update it doesn't work anymore.

Thanks for that.

**Comment by mrc4tt** [comment]
cc: @Salvatore-Als 

I think it will be updated, when hl2sdk is up2date.

**Comment by mrc4tt** [comment]
Released for Linux.

Windows is delayed atm.

**Comment by Salvatore-Als** [comment]
Hi,
I will do the windows update when I am on a windows computer, probably from Tuesday.
