### ISSUE TITLE
Set per server (rcon.txt)

### ISSUE THREAD

**Issue by mrc4tt** [Salvatore-Als/cs2-fake-rcon#2]
Hi,

Is it possible with this plugin, I can set it into *as* per server?
E.g param ^

**Comment by Salvatore-Als** [comment]
Hello,
What do you mean ? 
Can you give me an example please ?

**Comment by mrc4tt** [comment]
@Salvatore-Als 
Example `-fakercon rconpwd`

Optional command line -fakercon (if rcon.txt does not exist)

Output on CS2 server: `./cs2 -dedicated -game csgo -console -usercon +ip 127.0.0.1 -port 27515 +map de_dust2 -maxplayers 12 -fakercon rconpwd`

**Comment by Salvatore-Als** [comment]
I'ts not a bad idea, I will take a look asap but with no promise.
I do not plan to update the plugin, but keep you informed !

**Comment by mrc4tt** [comment]
I would like to have the opportunity to use it.

I have contacted you on Discord (If that's something we can discuss further.)

**Comment by mrc4tt** [comment]
Seems this will not be fixed as optional. ^
