### ISSUE TITLE
rcon.txt

### ISSUE THREAD

**Issue by pecagg** [Salvatore-Als/cs2-fake-rcon#3]
Hey,
Trying to install this on our scrim server hosted on CKRAS

I don't have permission to upload files to /bin/ folder, is there a workaround?

I managed to install metamod and it lists the fakercon plugin successfully.
![NksOzle](https://github.com/Salvatore-Als/cs2-fake-rcon/assets/23000095/f51d8328-64bd-4874-994a-625bef5a861c)
![image](https://github.com/Salvatore-Als/cs2-fake-rcon/assets/23000095/7067739e-abd0-4f1d-b210-7a8537810fac)

**Comment by mrc4tt** [comment]
@pecagg You can see under #2 

I have asked about this with optional commandline-parameter `-fakercon` e.g. As not all GSPs allow users to install ".txt" into /bin/ e.g :)

**Comment by Salvatore-Als** [comment]
I have implemented -fakercon as a command line, but working on a issue, the command is not sent to the server, idk why.
You will be informed once it's fixed :)

**Comment by Salvatore-Als** [comment]
Fixed since several ours :) 
Let you check the last release.
