### ISSUE TITLE
rcon.txt issue

### ISSUE THREAD

**Issue by Porcellacion** [Salvatore-Als/cs2-fake-rcon#4]
Most server providers won't let you add the rcon.txt into the bin/linuxsteamrt64.
There are often also limitations with the launch parameters with hosting providers.

Would you please mind updating the plugin so that it uses the same sv_password, or to make it possible to put the rcon.txt somewhere else?

**Comment by Salvatore-Als** [comment]
Hello, 
it's not possible for now, the HL2 SDK is not ready yet to manage the real convar :/

I plan to add a cache so as not to have to relog each time I change the map, I will add a more easily accessible configuration file :)

I keep you informed ! :)

**Comment by Salvatore-Als** [comment]
You can download the last release:

Moving configuration to /addons/metamod/config/fake_rcon
Create a cache system, to no longer have to type fake_rcon_password each time the map change
Add fake_rcon_clean_cache

Tutorial available here https://forums.alliedmods.net/showpost.php?p=2811082&postcount=15

**Comment by Porcellacion** [comment]
Amazing, thank you!
