### ISSUE TITLE
Custom password can't be used

### ISSUE THREAD

**Issue by W4iv3lt** [Salvatore-Als/cs2-fake-rcon#5]
I tried to change the password to a custom password but it is read incorrectly. In the log there are random symbols for the password:
Fake rcon is P��� The password has four letters and begins with s

**Comment by mrc4tt** [comment]
I detected this same problem already yesterday, I found out it happens after saving the file.

**Comment by Salvatore-Als** [comment]
Hello
Yes the file encoding can make a bug, working on this :)

**Comment by Salvatore-Als** [comment]
Fixed on the version 1.2.1 :)

**Comment by crashzk** [comment]
> Fixed on the version 1.2.1 :)

Windows?

**Comment by mrc4tt** [comment]
> > Fixed on the version 1.2.1 :)
> 
> Windows?

It coming tomorrow. ^ @crashzk

**Comment by Salvatore-Als** [comment]
Available now :)
