### ISSUE TITLE
Impossible de modifier le password

### ISSUE THREAD

**Issue by DEV-Velris** [Salvatore-Als/cs2-fake-rcon#6]
Hello,

J'ai mis le plugin et les fichiers de configuration dans le serveur. Mais je modifie le password dans le config.ini mais lors du lancement du serveur il garde le password par défaut, alors que le fichier est bien sauvegarder.

**Comment by Salvatore-Als** [comment]
Il n'y à pas de rcon par défaut, s'il garde le rcon du début, qui au final est le rcon présent dans le fichier, c'est que tu mets pas correctement à jour le fichier.

Il n'y a pas de rcon par défaut dans le plugin.

Vérifie que tu as les droits d'éditions sur ton fichier.

**Comment by DEV-Velris** [comment]
Voici le message console lors du start-up:
[FAKE RCON] Fetching RCON from addons/configs/fake_rcon/config.ini
[FAKE RCON] Fake rcon is rconconfig
Alors que voici le fichier:
"Config"
{
    "caching_time"	"120"
    "rcon_password"	"etherniacsrcon0980"
}

**Comment by Salvatore-Als** [comment]
Comme je l'ai dis, il n'y a pas de rcon par défaut dans le plugin.
`rconconfig` est le rcon par défaut dans le fichier.

Si au startup ça indique ce rcon c'est que, soit le fichier est mal modifié, soit tu as modifié un fichier qui n'est pas dans le bon dossier.

Vérifie le dossier, il doit être dans `/addons/configs/fake_rcon/config.ini`

**Comment by DEV-Velris** [comment]
![image](https://github.com/Salvatore-Als/cs2-fake-rcon/assets/86017918/a61921b2-bc9f-4637-886c-e90a59bef9e3)
En effet je suis bien dans /addons j'ai l'impression.
Si vous souhaitez m'expliquer plus vite en cas d'une erreur de ma part voici mon discord: velristv

**Comment by Salvatore-Als** [comment]
Vérifie avec `meta list` que tu es bien en version 1.1.2, auquel cas tu devrais faire un ticket chez ton hébergeur pour vérifier que le fichier est bien modifié

**Comment by DEV-Velris** [comment]
Voici la version
![image](https://github.com/Salvatore-Als/cs2-fake-rcon/assets/86017918/5c09d003-1fc9-4d17-8485-eba3f8ff1cf0)

**Comment by Salvatore-Als** [comment]
Dans ce cas tu dois contacter ton hébergeur pour s'assurer que tu as le droit d'éditer ton fichier et si le fichier est bien édité correctement

**Comment by Salvatore-Als** [comment]
Ah t'es chez VG, vas sur le discord VG et contact moi directement sur discord :)

**Comment by Salvatore-Als** [comment]
Tu édits pas le bon fichier, le fichier se trouve dans /game/csgo/addons, pas à la racine du serveur.

Je close :)
