### ISSUE TITLE
Windows release as .zip

### ISSUE THREAD

**Issue by CDWimmer** [Salvatore-Als/cs2-fake-rcon#8]
Hello,
Can you please release Windows versions as a .zip? I shouldn't have to install extra software just to unpackage this. It is not a large enough set of files to justify rar compression.

**Comment by Salvatore-Als** [comment]
Hello,
You don't need any extra tools, you can use this https://extract.me :)

**Comment by CDWimmer** [comment]
Completely forget about this sorry - Sure but I don't think I'm being unreasonable to expect all releases to be the same formats? if anything linux versions should be tarballed and Windows zipped
