### ISSUE TITLE
fake_rcon broken (latest CS2 update)

### ISSUE THREAD

**Issue by Porcellacion** [Salvatore-Als/cs2-fake-rcon#9]
This broke with the new MetaMod update

**Comment by mrc4tt** [comment]
I know, but we need someone to PR update for AMBuild (**I think**).

**Comment by mrc4tt** [comment]
@Porcellacion 

I will soon release it. I'm working on windows build (asap)

**Comment by Porcellacion** [comment]
Linux build please, that's what I'm using <3

**Comment by mrc4tt** [comment]
I will update you here (asap) ^

**Comment by Salvatore-Als** [comment]
Linux build available, windows will be available soon by @mrc4tt  :)

**Comment by Porcellacion** [comment]
Amazing!

**Comment by mrc4tt** [comment]
Windows is now released. :-)
